# Generated by Django 2.0.1 on 2018-01-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180131_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='readings',
            name='project_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readings',
            name='project_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
